sistema/libreria/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import static


urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('nosotros', views.nosotros, name='nosotros'),
    path('libros', views.libros, name='libros'),
    path('libros/crear', views.crear, name='crear'),
    path('libros/editar', views.editar, name='editar'),
    path('eliminar/<int:id>', views.eliminar, name='eliminar'), #Se elimina directamente el libro marcando el ID que corresponda
    path('libros/editar/<int:id>', views.editar, name='editar'),
    path('registros_usuarios/', views.registro_usuarios, name='registro_usuarios'),
    path('registros_usuarios/', views.registro_usuarios, name='registro_usuarios'), 
    path('ingreso_usuarios/', views.ingreso_usuarios, name='ingreso_usuarios'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sistema/sistema/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libreria.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #En el archivo urls.py, agrega las siguientes líneas al comienzo del archivo para que los archivos multimedia se sirvan correctamente en modo de desarrollo:

sistema/libreria/models.py
from django.db import models
from django.core.validators import EmailValidator

class Libro(models.Model):
    id= models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=100, verbose_name='Título')
    imagen = models.ImageField(upload_to='imagenes/', verbose_name="Imagen", null=True) #python -m pip install Pillow
    descripcion = models.TextField(verbose_name= "Descripción", null=True)
    archivo_pdf = models.FileField(upload_to='pdfs/', verbose_name='PDF del Libro', null=True) #pip install django-filebrowser
    
    def __str__(self):
        fila = "Título: " + self.titulo + " - " + "Descripción: " + self.descripcion
        return "Título: " + self.titulo + " - Descripción: " + self.descripcion



    def eliminar(self, using=None, keep_parents=False):
        self.imagen.storage.delete(self.imagen.name)
        super().delete()
        if self.imagen:
            self.imagen.storage.delete(self.imagen.name)
        if self.archivo_pdf:
            self.archivo_pdf.storage.delete(self.archivo_pdf.name)
        super().delete()

class UsuarioExterno(models.Model):
    NINGUNA = 'Ninguna'
    ESTUDIANTE = 'Estudiante'
    PROFESIONAL = 'Profesional'
    EDUCADOR = 'Educador'
    OPCIONES_PROFESION = (
        (NINGUNA, 'Ninguna'),
        (ESTUDIANTE, 'Estudiante'),
        (PROFESIONAL, 'Profesional'),
        (EDUCADOR, 'Educador'),
    )

    nombres = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField()
    edad = models.PositiveIntegerField()
    profesion = models.CharField(max_length=20, choices=OPCIONES_PROFESION, default=NINGUNA)
    rut = models.CharField(max_length=12)
    email = models.EmailField()
    confirmacion_email = models.EmailField()
    
    contraseña = models.CharField(max_length=128)
    confirmacion_contraseña = models.CharField(max_length=128)
    pais = models.CharField(max_length=50)
    region = models.CharField(max_length=50)
    comuna = models.CharField(max_length=50)
    codigo_postal = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.nombres} {self.apellidos}"

sistema/libreria/forms.py
from django import forms
from .models import Libro, UsuarioExterno


class LibroForm(forms.ModelForm):
    class Meta:
        model = Libro
        fields = '__all__' #Actualizara el formulario para incluir todos los campos

class RegistroUsuarioForm(forms.ModelForm):
    class Meta:
        model = UsuarioExterno
        fields = '__all__'

sistema/libreria/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Libro
from .forms import LibroForm
from .forms import RegistroUsuarioForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login
from datetime import datetime
from django.contrib import messages

def inicio(request):
    return render(request, 'paginas/inicio.html')
def nosotros(request):
    return  render(request, 'paginas/nosotros.html')

def libros(request):
    libros = Libro.objects.all()
    return render(request, 'libros/index.html', {'libros': libros})

def crear(request):
    if request.method == 'POST':
        formulario = LibroForm(request.POST or None, request.FILES or None) #Identifica todos los archivos que van al formulario y los que se envian
        if formulario.is_valid():
            formulario.save()
            return redirect('libros')
    else:
        formulario = LibroForm()
            
    return render(request, 'libros/crear.html', {'formulario': formulario}) 


def editar(request, id):
    libro = Libro.objects.get(id=id)
    formulario = LibroForm(request.POST or None, request.FILES or None, instance=libro)
    if formulario.is_valid() and request.POST:
        formulario.save()
        return redirect('libros')
    return render(request, 'libros/editar.html', {'formulario': formulario})

def eliminar(request, id):
    libro = Libro.objects.get(id=id)
    libro.delete()
    return redirect('libros') #Elimina el campo

def registro_usuarios(request):
    if request.method == 'POST':
        formulario = RegistroUsuarioForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect('ingreso_usuarios')
    else:
        formulario = RegistroUsuarioForm()

    return render(request, 'registros_usuarios.html', {'formulario': formulario})

def ingreso_usuarios(request):
    if request.method == 'POST':
        formulario = AuthenticationForm(data=request.POST)
        if formulario.is_valid():
            usuario = formulario.get_user()
            login(request, usuario)
            messages.success(request, 'Ingresaste con éxito!!!')
            return redirect('inicio.html')  # Reemplaza 'pagina_inicio' con la URL de tu página de inicio
    else:
        formulario = AuthenticationForm()

    return render(request, 'ingreso_usuarios.html', {'formulario': formulario})

def nosotros(request):
    current_year = datetime.now().year
    return render(request, 'paginas/nosotros.html', {'current_year': current_year})

sistema/libreria/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <title> {% block titulo %} {% endblock %} </title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS v5.2.1 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>

<nav class="navbar bg-dark border-bottom border-bottom-dark" data-bs-theme="dark">
    <ul class="nav">
        <li class="navbar navbar-expand-lg bg-body-tertiary">
            <a class="nav-link " border-box="1px" aria-current="page" href="{% url 'inicio' %}">Inicio </a>
        </li>
        <li class="navbar navbar-expand-lg bg-body-tertiary">
            <a class="nav-link " border-box="1px" href="{% url 'libros' %}">Libros </a>
        </li>
        <li class="navbar navbar-expand-lg bg-body-tertiary">
            <a class="nav-link " border-box="1px" href="{% url 'nosotros' %}">Nosotros </a>
        </li>
        <li class="navbar navbar-expand-lg bg-body-tertiary">
            <a class="nav-link " border-box="1px" aria-current="page" href="{% url 'registro_usuarios' %}">Registrarse</a>
        </li>
        <li class="navbar navbar-expand-lg bg-body-tertiary">
            <a class="nav-link " border-box="1px" aria-current="page" href="{% url 'ingreso_usuarios' %}">Ingresar</a>
        </li>
    </ul>
  
    
</nav>
<div class="container">
    <div class="row">
        <div class="col-12">

            <br />
            {% block contenido %} {% endblock %}
        </div>
    </div>
</div>





<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
    </script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
    </script>
</body>

</html>

sistema/libreria/templates/ingreso_usuarios.html
{% extends "base.html" %}

{% block titulo %}Ingreso de Usuarios{% endblock %}

{% block contenido %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-header">
                    <h3 class="text-center">Ingreso de Usuarios</h3>
                </div>
                <div class="card-body">
                    <!-- Aquí agregamos el bloque messages para mostrar el mensaje de éxito -->
                    {% if messages %}
                    <div class="alert alert-success">
                        <strong>{{ messages }}</strong>
                    </div>
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="email" class="form-label">Correo Electrónico</label>
                            <input type="email" class="form-control" id="email" name="email" required>
                        </div>
                        <div class="mb-3">
                            <label for="contraseña" class="form-label">Contraseña</label>
                            <input type="password" class="form-control" id="contraseña" name="contraseña" required>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Ingresar</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-muted">
                    <p class="text-center mb-0">¿No tienes una cuenta? <a href="{% url 'registro_usuarios' %}">Regístrate aquí</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

sistema/libreria/templates/libros/crear.html
{% extends "base.html" %}

{% block titulo %}Agregar nuevo libro{% endblock %}

{% block contenido %}

<div class="card">
    <div class="card-header">
        Crear un libro
    </div>
    <div class="card-body">
        <h4 class="card-title">Datos del libro</h4>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ formulario.as_p }}
            <button type="submit" class="btn btn-primary">Guardar</button>
        </form>
    </div>
    <div class="card-footer text-muted">
    </div>
</div>

{% endblock %}

sistema/libreria/templates/libros/editar.html
{% extends "base.html" %}

{% block titulo  %}  Editar libro  {% endblock %}

{% block contenido  %}  

<div class="card">
    <div class="card-header">
        Editar información del libro
    </div>
    <div class="card-body">
        <h4 class="card-title">Datos del libro</h4>
    {%  include 'libros/form.html' %}    
    </div>
    <div class="card-footer text-muted">
    </div>
</div>

{% endblock %}
    

sistema/libreria/templates/libros/form.html
<form enctype="multipart/form-data" method="post">
  {% csrf_token %}
  {% for campo in formulario %}
    <div class="mb-3">
      <label for="" class="form-label">{{ campo.label }}</label>
      
      {% if campo.field.widget.input_type == 'file' and campo.value %}
      <br/>
      <img src="{{MEDIA_URL}}/imagenes/{{campo.value}}" width="100" alt="" srcset="" >
      {% endif %}
      
      <input 
      type="{{ campo.field.widget.input_type }}" <--Todos los campo sirven para generar la subida de las imagenes
      class="form-control" 
      name="{{ campo.name}}" 
      id=" {{ campo.id}}" 
      aria-describedby="helpId" 
      placeholder="{{ campo.label}}" 
      value="{{ campo.value | default:'' }}" <--Informacion para revalidar que los datos escritos a actualizar son los mismos 
      
      />


    </div>
    <div class="col-12 "help-text"> {{campo.errors}} </div>
  {% endfor %}  
  <input name="" id="" class="btn btn-success" type="submit" value="Enviar información">
  <a name="" id="" class="btn btn-primary" href="{% url 'libros' %}" role="button">Cancelar</a>
</form>

sistema/libreria/templates/libros/index.html
{% extends "base.html" %}

{% block titulo %}Lista de libros{% endblock %}

{% block contenido %}

<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);"
    aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'inicio' %}">Inicio</a></li>
        <li class="breadcrumb-item active" aria-current="page">Lista de libros</li>
    </ol>
</nav>

<br>

<div class="card">
    <div class="card-header">
        <a name="" id="" class="btn btn-success" href="{% url 'crear' %}" role="button">Agregar nuevo libro</a>
    </div>
    <div class="card-body">
        <h4 class="card-title">Libros</h4>

        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Título</th>
                    <th>Imagen</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for libro in libros %}
                <tr>
                    <td>{{ libro.id }}</td>
                    <td>{{ libro.titulo }}</td>
                    <td>
                        <img src="{{ libro.imagen.url }}" height="100">
                    </td>
                    <td>{{ libro.descripcion }}</td>
                    <td>
                        <a name="" id="" class="btn btn-info" href="{% url 'editar' libro.id %}" role="button">Editar</a>
                        <br>
                        <a name="" id="" class="btn btn-danger" href="{% url 'eliminar' libro.id %}" role="button">Borrar</a>
                        <br>
                        {% if libro.archivo_pdf %}
                        <a name="" id="" class="btn btn-primary" href="{{ libro.archivo_pdf.url }}" role="button" download>Descargar</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>
    <div class="card-footer text-muted">

    </div>
</div>

{% endblock %}

sistema/libreria/templates/paginas/inicio.html
{% extends "base.html" %}

{% block titulo %} Inicio {% endblock %}

{% block contenido %}

<div class="p-5 bg-light">
    <div class="container">
        <h1 class="display-3"> ¡Bienvenido al mundo de la lectura y el conocimiento! </h1>
        <p class="lead"> Iniciando tu biblioteca personal: ¡Añade tus libros! </p>
        <hr class="my-2">
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'libros' %}" role="button">Empezar</a>
        </p>
    </div>
</div>

{% endblock %}

sistema/libreria/templates/paginas/nosotros.html
{% extends "base.html" %}

{% load static %}

{% block titulo %} Nosotros {% endblock %}

{% block contenido %}

<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);"
    aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'inicio' %}">Inicio</a></li>
        <li class="breadcrumb-item active" aria-current="page">Nosotros</li>
    </ol>
</nav>

<br>

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h1>Bienvenidos a nuestra biblioteca</h1>
            <p>En nuestra biblioteca, nos dedicamos a fomentar la cultura y el conocimiento a través de la lectura. Creemos que
                los libros son una herramienta fundamental para el desarrollo personal y profesional, y por eso trabajamos día a
                día para ofrecer a nuestros usuarios la mejor selección de títulos y servicios.</p>
            <!-- ... (Resto del contenido) ... -->
            <p>En definitiva, en nuestra biblioteca encontrarás mucho más que libros. Descubre todo lo que podemos ofrecerte y
                únete a nuestra comunidad de lectores y amantes de la cultura. ¡Te esperamos!</p>
        </div>
        
    </div>
</div>

<footer class="bg-dark text-white text-center py-3">
    <p class="mb-0">Todos los derechos reservados &copy; {{ current_year }}</p>
</footer>

{% endblock %}

sistema/libreria/templates/registros_usuarios.html
{% extends "base.html" %}

{% block titulo %}Registro de Usuarios{% endblock %}

{% block contenido %}
<div class="container mt-4">
  <h2 class="mb-4">Registro de Usuarios</h2>
  <form method="post">
    {% csrf_token %}
    <div class="row mb-3">
      <div class="col-md-6">
        <label for="id_nombres" class="form-label">Nombres</label>
        <input type="text" class="form-control" id="id_nombres" name="nombres" required>
      </div>
      <div class="col-md-6">
        <label for="id_apellidos" class="form-label">Apellidos</label>
        <input type="text" class="form-control" id="id_apellidos" name="apellidos" required>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-md-6">
        <label for="id_fecha_nacimiento" class="form-label">Fecha de Nacimiento</label>
        <div class="input-group date" id="datetimepicker">
          <input type="date" class="form-control" id="id_fecha_nacimiento" name="fecha_nacimiento" required>
          <span class="input-group-date">
            <i class="bi bi-calendar"></i>
          </span>
        </div>
      </div>
      <div class="col-md-6">
        <label for="id_edad" class="form-label">Edad</label>
        <input type="number" class="form-control" id="id_edad" name="edad" required>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-md-6">
        <label for="id_profesion" class="form-label">Profesión</label>
        <select name="profesion" id="id_profesion" class="form-select" required>
          <option value="" selected disabled>Selecciona una opción</option>
          <option value="Ninguna">Ninguna</option>
          <option value="Estudiante">Estudiante</option>
          <option value="Profesional">Profesional</option>
          <option value="Educador">Educador</option>
        </select>
        <div class="invalid-feedback">
          Debes seleccionar una profesión.
        </div>
      </div>
      <div class="col-md-6">
        <label for="id_rut" class="form-label">RUT</label>
        <input type="text" class="form-control" id="id_rut" name="rut" required>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-md-6">
        <label for="id_email" class="form-label">Email</label>
        <input type="email" class="form-control" id="id_email" name="email" required>
      </div>
      <div class="col-md-6">
        <label for="id_confirmacion_email" class="form-label">Confirmar Email</label>
        <input type="email" class="form-control" id="id_confirmacion_email" name="confirmacion_email" required>
      </div>
    </div>


    <div class="row mb-3">
      <div class="col-md-6">
        <label for="id_contraseña" class="form-label">Contraseña</label>
        <div class="input-group">
          <input type="password" class="form-control" id="id_contraseña" name="contraseña" required>
          <button class="btn btn-outline-secondary" type="button" id="verContraseña"
            onclick="verOcultarContraseña('id_contraseña')">Ver</button>
        </div>
      </div>
      <div class="col-md-6">
        <label for="id_confirmacion_contraseña" class="form-label">Confirmar Contraseña</label>
        <div class="input-group">
          <input type="password" class="form-control" id="id_confirmacion_contraseña" name="confirmacion_contraseña"
            required>
          <button class="btn btn-outline-secondary" type="button" id="verConfirmacionContraseña"
            onclick="verOcultarContraseña('id_confirmacion_contraseña')">Ver</button>
        </div>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-md-6">
        <label for="id_pais" class="form-label">País</label>
        <input type="text" class="form-control" id="id_pais" name="pais" required>
      </div>
      <div class="col-md-6">
        <label for="id_region" class="form-label">Región</label>
        <input type="text" class="form-control" id="id_region" name="region" required>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-md-6">
        <label for="id_comuna" class="form-label">Comuna</label>
        <input type="text" class="form-control" id="id_comuna" name="comuna" required>
      </div>
      <div class="col-md-6">
        <label for="id_codigo_postal" class="form-label">Código Postal</label>
        <input type="text" class="form-control" id="id_codigo_postal" name="codigo_postal" required>
      </div>
    </div>
</div>
<!-- Otros campos del formulario -->
<br>
<button type="submit" class="btn btn-primary">Registrarse</button>
</form>
</div>

<!-- Agregar los siguientes scripts al final del archivo -->
<script>
  function verOcultarContraseña(inputId) {
    var inputElement = document.getElementById(inputId);
    if (inputElement.type === "password") {
      inputElement.type = "text";
    } else {
      inputElement.type = "password";
    }
  }
</script>
<!-- Script de Bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

<!-- Script del datepicker -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

<script>
  // Inicializar el datepicker
  $('#datetimepicker').datepicker({
    format: 'yyyy-mm-dd',
    autoclose: true,
    todayHighlight: true
  });
</script>
{% endblock %}